#!/bin/bash
# ──────────────────────────────────────────────────────────────────
# AAIF MCP Server — Sandbox Environment Setup
# Run this on Day 1 to configure credentials and validate connectivity.
#
# Usage:
#   chmod +x scripts/setup_sandbox.sh
#   source scripts/setup_sandbox.sh
# ──────────────────────────────────────────────────────────────────

echo "╔══════════════════════════════════════════════════════════╗"
echo "║  AAIF MCP Server — Sandbox Configuration                ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

# ── Salesforce Sandbox ──────────────────────────────────────────
echo "── Salesforce Sandbox Credentials ──"
echo ""

if [ -z "$SFDC_INSTANCE_URL" ]; then
    read -p "  SFDC Instance URL (e.g., https://lf--sandbox.sandbox.my.salesforce.com): " SFDC_INSTANCE_URL
    export SFDC_INSTANCE_URL
fi
echo "  ✓ SFDC_INSTANCE_URL = $SFDC_INSTANCE_URL"

if [ -z "$SFDC_CLIENT_ID" ]; then
    read -p "  SFDC Connected App Client ID: " SFDC_CLIENT_ID
    export SFDC_CLIENT_ID
fi
echo "  ✓ SFDC_CLIENT_ID = ${SFDC_CLIENT_ID:0:12}..."

if [ -z "$SFDC_CLIENT_SECRET" ]; then
    read -sp "  SFDC Connected App Client Secret: " SFDC_CLIENT_SECRET
    echo ""
    export SFDC_CLIENT_SECRET
fi
echo "  ✓ SFDC_CLIENT_SECRET = ****"

if [ -z "$SFDC_USERNAME" ]; then
    read -p "  SFDC Integration User Email: " SFDC_USERNAME
    export SFDC_USERNAME
fi
echo "  ✓ SFDC_USERNAME = $SFDC_USERNAME"

if [ -z "$SFDC_PASSWORD" ]; then
    read -sp "  SFDC Password (+ security token appended): " SFDC_PASSWORD
    echo ""
    export SFDC_PASSWORD
fi
echo "  ✓ SFDC_PASSWORD = ****"

echo ""

# ── Groups.io ──────────────────────────────────────────────────
echo "── Groups.io Credentials ──"
echo ""

if [ -z "$GROUPSIO_API_TOKEN" ]; then
    read -sp "  Groups.io API Token: " GROUPSIO_API_TOKEN
    echo ""
    export GROUPSIO_API_TOKEN
fi
echo "  ✓ GROUPSIO_API_TOKEN = ${GROUPSIO_API_TOKEN:0:8}..."

if [ -z "$GROUPSIO_ORG_ID" ]; then
    read -p "  Groups.io Org ID (or press Enter to skip): " GROUPSIO_ORG_ID
    if [ -n "$GROUPSIO_ORG_ID" ]; then
        export GROUPSIO_ORG_ID
        echo "  ✓ GROUPSIO_ORG_ID = $GROUPSIO_ORG_ID"
    else
        echo "  ○ GROUPSIO_ORG_ID = (not set, will use group-level ops)"
    fi
fi

echo ""

# ── Write .env file for docker-compose ─────────────────────────
ENV_FILE="$(dirname "$0")/../.env"
cat > "$ENV_FILE" << EOF
# AAIF MCP Server — Sandbox Environment
# Generated by setup_sandbox.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT COMMIT THIS FILE

SFDC_INSTANCE_URL=$SFDC_INSTANCE_URL
SFDC_CLIENT_ID=$SFDC_CLIENT_ID
SFDC_CLIENT_SECRET=$SFDC_CLIENT_SECRET
SFDC_USERNAME=$SFDC_USERNAME
SFDC_PASSWORD=$SFDC_PASSWORD
GROUPSIO_API_TOKEN=$GROUPSIO_API_TOKEN
GROUPSIO_ORG_ID=$GROUPSIO_ORG_ID
AAIF_MCP_LOG_LEVEL=DEBUG
EOF

echo "── Environment file written to .env ──"
echo ""

# ── Update .gitignore ──────────────────────────────────────────
GITIGNORE="$(dirname "$0")/../.gitignore"
if ! grep -q "^\.env$" "$GITIGNORE" 2>/dev/null; then
    echo ".env" >> "$GITIGNORE"
    echo "  ✓ Added .env to .gitignore"
fi

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║  Setup complete! Next steps:                            ║"
echo "║                                                         ║"
echo "║  1. Run connectivity check:                             ║"
echo "║     python scripts/validate_sandbox.py                  ║"
echo "║                                                         ║"
echo "║  2. If all green, start the server:                     ║"
echo "║     python -m aaif_mcp_server                           ║"
echo "║                                                         ║"
echo "║  3. Or use docker-compose:                              ║"
echo "║     docker-compose up                                   ║"
echo "╚══════════════════════════════════════════════════════════╝"
